defaults: &defaults
  product_name: 家計簿 さな太郎
  system_mail_address: donotreply@nu-chon.org
  effect:
    pulsate:
      duration: 300
      times: 3
    fade:
      duration: 300
    slide:
      duration: 200
    highlight:
      duration: 1000
      color: "#ff99ff"
  item_list_count: 20
  enable_tweet: true
  api_auth:
    oauth: true
    basic: false
    session: true

development:
  <<: *defaults
  item_list_count: 100
  admin_user: "admin"
  admin_password: "password"
  oauth_admin_user: "admin"
  oauth_admin_password: "password"
test:
  <<: *defaults
  api_auth:
    oauth: true
    basic: true
    session: true
  
production:
  <<: *defaults
  item_list_count: 200
